### ISSUE TITLE
Virtual rides no longer hidden

### ISSUE THREAD

**Issue by adamwoodnz** [Strajk/strava-enhancement-suite#110]
I'm on version 2.20.1 running in Brave browser, but this is reproducible in Chrome too.

I have the setting enabled:
<img width="664" alt="Screen Shot 2021-09-08 at 1 17 43 PM" src="https://user-images.githubusercontent.com/1017872/132430474-f947fe18-9dcd-4ce8-9457-3c4f13d01d12.png">

But I'm still seeing Virtual rides:
<img width="575" alt="Screen Shot 2021-09-08 at 1 18 09 PM" src="https://user-images.githubusercontent.com/1017872/132430529-211a9eda-bc21-4a5d-9fcc-7b8875848f7b.png">

I'm not aware of how these are being hidden, but maybe a CSS selector has changed or similar?

**Comment by Strajk** [comment]
@adamwoodnz hey and kudos for your bug report :)))

This project was not my prio lately, but with arrival of winter, virtual rides spree on strava got annoying enough for me to fix this :) https://github.com/Strajk/strava-enhancement-suite/commit/4e4fd101036e52654455e0f36e475f10a6d86ebb

It should be published automatically in few hours on BETA version of the extension https://chrome.google.com/webstore/detail/strava-enhancement-suite/oaioodcklbhlefejbglemgjndhckgklf
