### ISSUE TITLE
Add `myself` as maintainer 🙏

### ISSUE THREAD

**Issue by Strajk** [Strajk/strava-enhancement-suite#92]
- Google: straaajk@gmail.com (triple `a` is correct)
- Keybase (for chat and secrets sharing) https://keybase.io/strajk

**Comment by lamby** [comment]
Hm, so I can easily transfer the Github repo, but I am finding it hard to find out to cleanly move the chrome extension.

Okay, I think I need to use https://support.google.com/chrome_webstore/contact/dev_account_transfer

This will likely require you to be a signed up as a Chrome Web Store 'Publisher' first. Can you confirm?

**Comment by Strajk** [comment]
Confirming that I have developer account set up @lamby 

![image](https://user-images.githubusercontent.com/697301/87306030-b6cc8d80-c517-11ea-88ef-0bfc898bd526.png)

**Comment by lamby** [comment]
Done. Lets see how this goes..

**Comment by Strajk** [comment]
:yay: awesome, thanks – I'll do my best :)

Not showing up in my Developer Dashboard just yet, will let you know when it will appear 👀

**Comment by lamby** [comment]
Ah, right, it said it would take a while. And then it said it would take extra time due to COVID-19.

**Comment by Strajk** [comment]
Mmm interesting to know that there are still humans involved in this :)

How do you wanna proceed with the repo? I already have some more branches ready to push 😅

**Comment by lamby** [comment]
I was planning on waiting for the extension to transfer.

**Comment by Strajk** [comment]
👍 makes sense!

looking forward :))

**Comment by Strajk** [comment]
No action required ℹ️

Just letting you know that I've added the suffix `-fork` to my forked repo for now and I'm doing the development there without spamming you with PRs :))

I'll definitely be glad for any input & feedback – anytime – but I also understand that's hard to do when you no longer use the extension.

I've added some basic unit tests (for `keySort` as I struggled to understand that at first) and also basic UI tests with Cypress (when fixing prefilling manual activity from URLs params, as I was worried I might break something).

But I also try to avoid adding too much tooling and abstractions, as I like how developer-friendly the codebase is and I wanna keep it that way :)

![image](https://user-images.githubusercontent.com/697301/87442131-3596f880-c5f4-11ea-984e-2e6d7f1b2351.png)

**Comment by Strajk** [comment]
@lamby heya 👋 any news from Google overlords? :) 

In the meantime, I've created **Strava Enhancement Suite BETA** extension, which is automatically released and published via GitHub Actions from `develop` branch, where I'm adding new features.

I'm planning to share the beta with a few friends and maybe some enthusiasts from Reddit, and only merge new features into the main extension after some testing and feedback. After all, the extension has a pretty big user base and I don't wanna treat them as testers :D 

any thoughts?

**Comment by lamby** [comment]
No thoughts from me.. Good luck. :+1:

**Comment by Strajk** [comment]
@lamby hi there 👋  It's more than 3 weeks since the request – I think it's time to consider the possibility that not all things work perfectly even at Google and maybe something broke along the way 🙈

I've noticed that they changed the transfer process slightly (maybe just visually), can you please try again? :)

![](https://user-images.githubusercontent.com/697301/89517256-be5f1980-d7d9-11ea-95f1-2142fc968515.png)

https://support.google.com/chrome_webstore/contact/one_stop_support

`straaajk@gmail.com`

Can't wait to publish the new stuff :))

**Comment by lamby** [comment]
![image](https://user-images.githubusercontent.com/133209/89527180-d38b7680-d7e0-11ea-9d1b-079d99a1458b.png)
![image](https://user-images.githubusercontent.com/133209/89527192-d7b79400-d7e0-11ea-9180-8d6cff5a1587.png)

**Comment by Strajk** [comment]
Amazing – thank you!

**Comment by lamby** [comment]
FYI just received an email back:
![image](https://user-images.githubusercontent.com/133209/90310496-bf82fb80-dee9-11ea-801e-acc55d21ec00.png)

Have replied with all relevant info.

**Comment by Strajk** [comment]
@lamby ⌘C ⌘V "Amazing – thank you!" 😄

I went through all the features and adjusted them to the current state of Strava website, cannot wait to release it :)

**Comment by lamby** [comment]
![image](https://user-images.githubusercontent.com/133209/90340781-83878d80-dff2-11ea-92e1-55ef3f7524a8.png)

**Comment by Strajk** [comment]
@lamby Yay, it's there! 🙏 

![image](https://user-images.githubusercontent.com/697301/90431120-d6cc0f80-e0c8-11ea-9c61-dd614d2f9082.png)

Thank you so much, it really **means a lot for me**. 
I've always wanted some pet project that helps a lot of people.

Before finding Strava En. Suite, I've almost started creating my own extension, I'm so glad that I've done some searching beforehand :) I would have started with some modern hipster boilerplate - webpack, svelte, Rx and so on - and it would probably cause more harm than good. I have to admin that good ol' jQuery is the best tool for this kind of job, still, to this day.

By the way, I've been software engineer for almost 10 years now, but started contributing to open source just a few months ago and… my experience is amazing so far! Thank you also for that :)

I know that you said that you no longer use Strava (and this extension), but if you ever come back, feel free to let me know here on GitHub or ping me at https://twitter.com/straaajk ... you will be more that welcome :) 

Kudos for amazing job on the codebase :)

**Comment by lamby** [comment]
:+1: :+1: :+1: 

Oh, just to transfer the repo, I am seeing this:

![image](https://user-images.githubusercontent.com/133209/90437628-9b324500-e0ca-11ea-8f6a-421f7154e5cc.png)

Can you work out why? (I guess you might need to rename your fork temporarily...)

**Comment by Strajk** [comment]
@lamby should work now. My form already had `-for` suffix in the name, but that was not enough – I had to remove the whole repo first.

**Comment by lamby** [comment]
Cool, "request sent"

**Comment by Strajk** [comment]
Yay again, it worked :)))

**Comment by lamby** [comment]
Awesome; closing this ticket.
